# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FastPaste.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        MainWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(0, 0, 400, 500))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.treeWidget.header().setVisible(False)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FastPaste"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "1"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "1.1"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "1.2"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "1.3"))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "1.4"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "2"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "2.1"))
        self.treeWidget.topLevelItem(1).child(0).child(0).setText(0, _translate("MainWindow", "2.1.1"))
        self.treeWidget.topLevelItem(1).child(0).child(1).setText(0, _translate("MainWindow", "2.1.2"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "2.2"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "2.3"))
        self.treeWidget.topLevelItem(1).child(3).setText(0, _translate("MainWindow", "2.4"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "3"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "4"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "5"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("MainWindow", "6"))
        self.treeWidget.topLevelItem(6).setText(0, _translate("MainWindow", "7"))
        self.treeWidget.topLevelItem(7).setText(0, _translate("MainWindow", "8"))
        self.treeWidget.topLevelItem(8).setText(0, _translate("MainWindow", "9"))
        self.treeWidget.topLevelItem(9).setText(0, _translate("MainWindow", "0"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
