# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PhraseEditorUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os


class Ui_PhraseEditor(object):
    def setupUi(self, PhraseEditor):
        PhraseEditor.setObjectName("PhraseEditor")
        PhraseEditor.resize(500, 400)
        self.centralwidget = QtWidgets.QWidget(PhraseEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        #self.treeWidget = QtWidgets.QTreeWidget(self.splitter)
        self.treeWidget.setObjectName("treeWidget")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 17))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        #self.textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        #self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        PhraseEditor.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(PhraseEditor)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        PhraseEditor.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionaddPhrase = QtWidgets.QAction(PhraseEditor)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(os.path.dirname(__file__), "Images/addFile.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionaddPhrase.setIcon(icon)
        self.actionaddPhrase.setObjectName("actionaddPhrase")
        self.actionremovePhrase = QtWidgets.QAction(PhraseEditor)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.join(os.path.dirname(__file__),"Images/removeFile.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionremovePhrase.setIcon(icon1)
        self.actionremovePhrase.setObjectName("actionremovePhrase")
        self.actionsave = QtWidgets.QAction(PhraseEditor)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(os.path.join(os.path.dirname(__file__), "Images/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsave.setIcon(icon2)
        self.actionsave.setObjectName("actionsave")
        self.actionback = QtWidgets.QAction(PhraseEditor)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(os.path.join(os.path.dirname(__file__),"Images/back_color.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionback.setIcon(icon3)
        self.actionback.setObjectName("actionback")
        self.actionforward = QtWidgets.QAction(PhraseEditor)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(os.path.join(os.path.dirname(__file__),"Images/forward_color.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionforward.setIcon(icon4)
        self.actionforward.setObjectName("actionforward")
        self.toolBar.addAction(self.actionaddPhrase)
        self.toolBar.addAction(self.actionremovePhrase)
        self.toolBar.addAction(self.actionsave)
        self.toolBar.addAction(self.actionback)
        self.toolBar.addAction(self.actionforward)

        self.retranslateUi(PhraseEditor)
        QtCore.QMetaObject.connectSlotsByName(PhraseEditor)

    def retranslateUi(self, PhraseEditor):
        _translate = QtCore.QCoreApplication.translate
        PhraseEditor.setWindowTitle(_translate("PhraseEditor", "Редактировать фразы"))
        self.label.setText(_translate("PhraseEditor", "Шаблонная фраза"))
        self.label_2.setText(_translate("PhraseEditor", "Название"))
        self.toolBar.setWindowTitle(_translate("PhraseEditor", "toolBar"))
        self.actionaddPhrase.setText(_translate("PhraseEditor", "addPhrase"))
        self.actionaddPhrase.setToolTip(_translate("PhraseEditor", "Добавить"))
        self.actionremovePhrase.setText(_translate("PhraseEditor", "removePhrse"))
        self.actionremovePhrase.setToolTip(_translate("PhraseEditor", "Удалить"))
        self.actionsave.setText(_translate("PhraseEditor", "save"))
        self.actionsave.setToolTip(_translate("PhraseEditor", "Сохранить"))
        self.actionback.setText(_translate("PhraseEditor", "back"))
        self.actionback.setToolTip(_translate("PhraseEditor", " Назад"))
        self.actionforward.setText(_translate("PhraseEditor", "forward"))
        self.actionforward.setToolTip(_translate("PhraseEditor", "Вперед"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PhraseEditor = QtWidgets.QMainWindow()
    ui = Ui_PhraseEditor()
    ui.setupUi(PhraseEditor)
    PhraseEditor.show()
    sys.exit(app.exec_())
